---

- name: Retrieve VPN confile from the jump host
  slurp:
    src: "{{ ovpn_file_path }}"
  register: ovpn_file
  delegate_to: "{{ vpn_server_host }}"
  run_once: true

- name: Copy ovpn file to destination
  copy:
    dest: "{{ ovpn_file_path }}"
    content: "{{ ovpn_file.content | b64decode }}"
    mode: '0600'
