- src: galaxyproject.galaxy
  version: 0.10.14
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: geerlingguy.pip
  version: 2.0.0
- src: galaxyproject.miniconda
  version: 0.3.1
#- src: laniakea.galaxy_interactive_tools
# - src: usegalaxy_eu.galaxy_systemd
- src: usegalaxy_eu.certbot
  version: 0.1.5
# - src: galaxyproject.proftpd
- name: galaxyproject.tusd
  version: 0.0.1
- src: galaxyproject.cvmfs
  version: 0.2.14
       

