- name: galaxyproject.galaxy
  src: https://github.com/galaxyproject/ansible-galaxy
  version: 0.12.3
- name: galaxyproject.nginx
  src: https://github.com/galaxyproject/ansible-nginx 
  version: 0.7.1
- name: galaxyproject.postgresql
  src: https://github.com/galaxyproject/ansible-postgresql
  version: 1.1.8
- name: galaxyproject.postgresql_objects
  src: https://github.com/galaxyproject/ansible-postgresql-objects
  version: 1.2.1
- src: geerlingguy.pip
  version: 3.1.0
- name: galaxyproject.miniconda
  src: https://github.com/galaxyproject/ansible-miniconda
  version: 0.3.1
#- src: laniakea.galaxy_interactive_tools
# - src: usegalaxy_eu.galaxy_systemd
- name: usegalaxy_eu.certbot
  src: https://github.com/usegalaxy-eu/ansible-certbot
  version: 0.1.11
# - src: galaxyproject.proftpd
- name: galaxyproject.tusd
  src: https://github.com/galaxyproject/ansible-role-tusd
  version: 0.0.1
- name: galaxyproject.cvmfs
  src: https://github.com/galaxyproject/ansible-cvmfs
  version: 0.3.0
