- src: galaxyproject.galaxy
  version: 0.11.1
- src: galaxyproject.nginx
  version: 1.0.0
- src: galaxyproject.postgresql
  version: 1.1.6
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: geerlingguy.pip
  version: 3.1.0
- src: galaxyproject.miniconda
  version: 0.3.1
#- src: laniakea.galaxy_interactive_tools
# - src: usegalaxy_eu.galaxy_systemd
- src: usegalaxy_eu.certbot
  version: 0.1.11
# - src: galaxyproject.proftpd
- name: galaxyproject.tusd
  version: 0.0.1
- src: galaxyproject.cvmfs
  version: 0.3.0
