- hosts: laniakea-dashboard
  vars:
    bastion_host: elixir-paas
    wireguard_peer: "{{ wireguard_bastions[bastion_host] | combine({'bastion_host': bastion_host}) }}"
  roles:
    - ansible-role-laniakea-wireguard-setup
