---
- name: Ensure OpenVPN is installed on the bastion
  package:
    name: openvpn
    state: present

- name: Deploy server_orchdash.conf from template
  template:
    src: server_orchdash.conf.j2
    dest: "{{ openvpn_server_dir }}/{{ openvpn_server_config }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart openvpn server

- name: Enable and start the OpenVPN server service
  systemd:
    name: "{{ openvpn_service_name }}"
    enabled: true
    state: started

- name: Add extra subnet rules to openvpn iptables unit
  lineinfile:
    path: /etc/systemd/system/openvpn-iptables.service
    insertafter: "RemainAfterExit=yes"
    line: "{{ item }}"
  loop:
    - "ExecStart=/sbin/iptables -w 5 -I FORWARD -s {{ openvpn_server_subnet }}/24 -d {{ tenant_network }}/{{ tenant_prefix }} -j ACCEPT"
    - "ExecStart=/sbin/iptables -w 5 -t nat -A POSTROUTING -s {{ openvpn_server_subnet }}/24 -d {{ tenant_network }}/{{ tenant_prefix }} -o {{ openvpn_tenant_iface }} -j MASQUERADE"
    - "ExecStop=/sbin/iptables -w 5 -D FORWARD -s {{ openvpn_server_subnet }}/24 -d {{ tenant_network }}/{{ tenant_prefix }} -j ACCEPT"
    - "ExecStop=/sbin/iptables -w 5 -t nat -D POSTROUTING -s {{ openvpn_server_subnet }}/24 -d {{ tenant_network }}/{{ tenant_prefix }} -o {{ openvpn_tenant_iface }} -j MASQUERADE"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart openvpn-iptables service
  systemd:
    name: openvpn-iptables
    state: restarted
