---
- hosts: default
  tasks:
    - name: 'Inject laniakea-robot ssh public key - root'
      authorized_key:
        user: 'root'
        key: '{{ laniakea_robot_key_pub }}'
      ignore_errors: true
