---
- hosts: default
  become: true
  become_user: root
  vars:
    # SSH laniakea robot key
    laniakea_robot_key_pub: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH1TyGvTGFzEBK2lSrcCvKVTQiA7jLQJYIPlsWZcyQzfgDhcJEBt93wJpj9cn8rnJHFFwnoRWfMSZqUn0VD+tByIWdi32fgjD/+6zUbyZojFAiiIQN80/8toktw7duynpDJPNgRt6a7PnsFX24s1jhkN8WZShRf6SpubRAUyxgj6Zuz7KQtieY2x2YRdAAXsKpnOGbMi2mE5G+PLVx/t3FzcHheDqNPz6R5j0Ikq/uiobd+E1hwCCW+P8+qa+OPnrhvuNf24mOApwGvEkKDELHJotTLAdCmfbhpuBqTx3BICPikdzOwpJ4tCierU+SxD1wy7ffCEonrEwNN7gBiT9d'
  pre_tasks:
    - name: 'Inject laniakea-robot ssh public key for debug - root'
      authorized_key:
        user: 'root'
        key: '{{ laniakea_robot_key_pub }}'
      ignore_errors: true
    - name: '[EL] Install Packages for Rocky Linux'
      ansible.builtin.dnf:
        name: ['langpacks-en', 'glibc-all-langpacks', 'epel-release', 'python3-wheel-wheel']
        enablerepo: crb
        state: present
    - name: Install python3-virtualenv
      yum:
        name: python3-virtualenv
        enablerepo: epel-release
        state: present
    - name: '[EL] Install Galaxy Dependencies'
      package:
        name:  ['acl', 'bzip2', 'git', 'make', 'python-psycopg2', 'python3-psycopg2', 'tar', 'pip',  'gcc', 'openssl-devel', 'bzip2-devel', 'libffi-devel', 'zlib-devel', 'xz-devel', 'sqlite-devel', 'wget']
    - name: Install pgdg repository package (RedHat)
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm   
        disable_gpg_check: True
    - name: '[EL] update ca-certificates'
      command: 'yum update -y ca-certificates'
        #- name: '[EL] Add NGINX repository'
        #  command: 'yum-config-manager --add-repo https://depot.galaxyproject.org/yum/galaxy.repo'
        ##- name: '[EL] Install virtualenv for python3'
        #command: /usr/bin/pip3 install virtualenv
    - name: '[EL] Disable SELinux'
      selinux:
        state: disabled
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres      
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: galaxy
    - galaxyproject.nginx
      #- role: laniakea.galaxy_interactive_tools
      #when: enable_interactive_tools

  post_tasks:

    # Wait Galaxy and Conda
    # Galaxy here is configured for listening on TPC 4001 port.
    # It is configured to gunicorn socket file bind with ansible at deploy time.
    - name: 'Wait Galaxy'
      wait_for:
        host: 127.0.0.1
          port: '4001'
        timeout: 15000
    - name: lock-file absent 
      file:
        path: /export/tool_deps/conda.lock 
        state: absent

    # Stop services
    - name: stop galaxy
      command: "/usr/local/bin/galaxyctl -c /home/galaxy/galaxy/config/galaxy.yml stop"
      become: yes
    - name: stop TUSd
      systemd:
        state: stopped
        enabled: false
        name: galaxy-tusd
    - name: stop nginx
      systemd:
        state: stopped
        enabled: false
        name: nginx
    - name: stop postgresql
      systemd:
        state: stopped
        enabled: false
        name: postgresql-13
    - name: stop docker.service
      systemd:
        state: stopped
        enabled: false
        name: docker.service
      when: enable_interactive_tools
    - name: stop docker.socket
      systemd:
        state: stopped
        enabled: false
        name: docker.socket
      when: enable_interactive_tools

    # Clean the environment
    # Otherwise conda will start to install in temp directory
    - name: 'Clean /export content'
      file:
        state: absent
        path: '{{ export_dir }}'
