---
- hosts: default

  pre_tasks:
    - name: Install Packages for Rocky Linux
      dnf:
        name:
          - hdf5-devel 
        state: present

  roles:
    - role: ansible-role-laniakea-rstudio
      become: yes

  post_tasks:
    - name: Stop rstudio-server
      systemd:
        state: stopped
        enabled: no
        name: rstudio-server.service
      become: yes
